-- Cairn walking skeleton — the signed event envelope (Spike 0001 §3, §4).
--
-- This is the *day-one, can't-retrofit* shape: every column here is reserved
-- because an append-only log cannot grow these later without rewriting history
-- (the same reason t_effective and the encryption-capable body slot are day-one
-- in data-model §3.5/§3.6/§3.8). The walking skeleton exists to exercise this
-- shape on real hardware over a real link before it is frozen into an ADR.
--
-- Relationship to poc/replication-failover: that PoC proved set-union
-- convergence with a *bare* event_log (no signatures, projections-as-views).
-- This skeleton wraps the signed COSE_Sign1 envelope around the same HLC-ordered
-- log, adds an in-database content-address invariant, a trigger-maintained
-- projection (002), and a BLAKE3 content-addressed blob tier (003).
--
-- Target: PostgreSQL >= 18 (uuidv7(), the project floor). Loaded identically
-- into every node; a node's identity is just the string it stamps on origin.

BEGIN;

-- Content-addressing and the legibility twin lean on pgcrypto's digest().
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Maximum size of one signed event, enforced at EVERY admission door (submit_event,
-- submit_node_event, apply_remote_node_event, restore_node_event). This is the WRITE-side
-- counterpart of the wire/backup read caps (sync.rs MAX_FRAME_BYTES / medium.rs
-- MAX_CHUNK_BYTES, both 8 MiB): those caps REFUSE an oversized event on read, and because
-- a puller aborts mid-stream without checkpointing, a single oversized-but-admitted event
-- would wedge sync at that seq forever AND could clobber a good backup medium. Refusing
-- oversize at admission makes that unreachable — the read caps become true dead paths for
-- honest data. Set below the 8 MiB (8,388,608-byte) frame cap with headroom for framing.
-- (Review finding A7a. Attachments are content-addressed blobs on the byte tier, NOT
-- inlined here, so a legitimate clinical event never approaches this bound — ADR-0013.)
CREATE OR REPLACE FUNCTION cairn_max_event_bytes()
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 8000000 $$;

-- The clock-drift admission ceiling (issue #102), in milliseconds. The largest amount
-- a REMOTE event's asserted HLC wall may sit ahead of THIS node's own wall clock and
-- still be trusted to advance the local clock. Both remote-apply doors merge the local
-- HLC forward with GREATEST(local_wall, remote_wall) (the A3 invariant — the clock never
-- falls behind an accepted event); without a ceiling, ONE verified event from a
-- trusted-but-broken or hostile peer carrying an absurd future wall (e.g. 2^62 ms ≈ 146
-- million years) permanently ratchets this node's clock — and, on the node plane, poisons
-- trust_peer's `ORDER BY hlc_wall DESC` — into the far future, with no self-healing path
-- (GREATEST is monotone; real time never catches up). 24h is deliberately generous: it
-- admits any plausible honest clock skew (an unsynced peer, a timezone-as-UTC bug, an
-- offline node whose RTC drifted) — consonant with ADR-0027, where a low-confidence clock
-- is BRACKETED, never treated as falsification — while still defeating the ratchet: an
-- attacker can push the local clock at most ~24h past real time, and that excess decays as
-- real time advances, rather than persisting for geological spans. Measured against
-- clock_timestamp() (the node's own wall clock), NOT the possibly-already-advanced
-- hlc_state, so the bound is absolute rather than itself ratchetable. Applies ONLY to the
-- remote-apply doors: a node's own authored events are its own clock's truth
-- (node_hlc_tick is already bounded by the local clock_timestamp).
CREATE OR REPLACE FUNCTION cairn_max_hlc_drift_ms()
RETURNS bigint LANGUAGE sql IMMUTABLE AS $$ SELECT 86400000 $$;  -- 24 * 60 * 60 * 1000

-- ---------------------------------------------------------------------------
-- The append-only, signed clinical event log (governing principle #1).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_log (
    -- Identity & causal order ------------------------------------------------
    event_id        UUID    PRIMARY KEY,        -- UUIDv7, generated by the signer; INSIDE the signed bytes
    patient_id      UUID    NOT NULL,           -- the immortal subject UUID this event is about
    event_type      TEXT    NOT NULL,           -- 'identity.registration.asserted' | 'demographic.*' | 'clinical.*' | ...
    schema_version  TEXT    NOT NULL,           -- §3.13 join key; additive-only evolution

    -- Bitemporal time (§3.6): t_recorded is the HLC ceiling; t_effective is the
    -- freely-backdatable *claim* (NULL = not asserted / unknown — principle 4).
    hlc_wall        BIGINT  NOT NULL,           -- t_recorded: physical component (ms)
    hlc_counter     INTEGER NOT NULL,           -- t_recorded: logical tiebreak
    node_origin     TEXT    NOT NULL,           -- which node FIRST recorded (third sort key)
    t_effective     TIMESTAMPTZ,                -- asserted effective time; NULL-able on purpose

    -- The signed artifact (§4, structural move 1) ----------------------------
    -- signed_bytes IS the event: a COSE_Sign1 (RFC 9052) wire blob whose payload
    -- is the canonical-CBOR body. It is stored verbatim and NEVER re-serialized;
    -- everything below is a *derived view* of it, for indexing and projection.
    signed_bytes    BYTEA   NOT NULL,
    -- Self-describing content address (§4 move 2): multihash(sha2-256) of the
    -- signed bytes. The hash IS the event's identity, exactly as in §3.14.
    content_address BYTEA   NOT NULL UNIQUE,

    -- Derived view of the signed body (JSONB) — parsed FROM signed_bytes by the
    -- applying node, never authoritative, never round-tripped back to bytes.
    body            JSONB   NOT NULL,
    -- §3.9 contributor set (skeleton: a single author is enough). signer_key_id
    -- selects the verifying key; verification happens on apply (Bet A2), and in
    -- production moves in-DB via the ADR-0002 pgrx hatch (see note below).
    contributors    JSONB   NOT NULL,
    signer_key_id   TEXT    NOT NULL,

    -- §3.13 mandatory plaintext legibility twin (also the FTS/RAG substrate).
    plaintext_twin  TEXT    NOT NULL,

    -- Encryption-capable body slot (§3.8 / ADR-0005), stubbed off in the
    -- skeleton: sealed=false, dek_wrapped=NULL. Reserved day-one so crypto-shred
    -- can be added without an envelope change.
    sealed          BOOLEAN NOT NULL DEFAULT FALSE,
    dek_wrapped     BYTEA,

    -- §3.14 attachment references: an array of {alg, digest, media_type,
    -- descriptor}. The reference is eager (here); the BYTES are lazy (003).
    attachments     JSONB   NOT NULL DEFAULT '[]'::jsonb,

    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),  -- local arrival

    -- Content-address invariant, enforced in the database (§4 move 1 + §3.14):
    -- a row whose advertised address does not match its bytes is refused at the
    -- boundary. multihash prefix 0x12 0x20 = sha2-256, 32 bytes.
    CONSTRAINT event_content_addressed
        CHECK (content_address = '\x1220'::bytea || digest(signed_bytes, 'sha256')),
    -- t_recorded is a ceiling: the asserted effective time may precede it
    -- (backdating is legal) but the log never claims to have recorded the
    -- future. Clashes are flagged elsewhere, never auto-resolved (§3.6).
    CONSTRAINT hlc_nonnegative CHECK (hlc_wall >= 0 AND hlc_counter >= 0),
    -- The attachments column is a PROJECTION for querying, not the authoritative body —
    -- signed_bytes is. Every reader walks it with jsonb_array_elements, which raises 22023
    -- (NOT P0001, so cairn-sync freezes rather than pens) on a scalar or an object. Since
    -- #460 the apply door ADMITS a body whose attachments is not a list, so without this the
    -- malformed value would be stored and the refusal merely RELOCATED — out of a door that
    -- pens, names and reports it, into read paths with no handling at all, one of which is
    -- the §5.3/§5.8 search-before-create funnel (crates/cairn-node/src/patient/search.rs).
    -- Both doors coerce through cairn_json_list_or_empty, so a non-list can now only arrive
    -- through a CODE defect; this constraint is what makes that defect loud instead of silent.
    CONSTRAINT event_attachments_is_a_list CHECK (jsonb_typeof(attachments) = 'array')
);

-- Paired ALTER for databases created before the constraint existed (#207's rule: a widened
-- CREATE TABLE that is only replayed, never re-created, needs an explicit ALTER or existing
-- databases silently keep the old shape). ADD CONSTRAINT has no IF NOT EXISTS, so the guard is
-- an explicit catalogue check; it validates existing rows, which is safe because the strict
-- learner refused every non-list body before #460 and both doors coerce after it.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                    WHERE conrelid = 'event_log'::regclass
                      AND conname = 'event_attachments_is_a_list') THEN
        ALTER TABLE event_log
            ADD CONSTRAINT event_attachments_is_a_list
            CHECK (jsonb_typeof(attachments) = 'array');
    END IF;
END $$;

-- The responsibility proof travels WITH the event (issue #91 / review A2+M7). A
-- suppressing event (or any asserted responsibility) is admitted only against a valid
-- human attestation token bound to its content-address; if that token were verified
-- and discarded (the pre-#91 behavior), a downstream node re-serving the event could
-- never re-prove the responsibility, and the apply door could not re-run the gate.
-- So the token (and the attester's pubkey) are stored beside the signed bytes and
-- shipped on the clinical sync wire. NULL for events that needed no attestation.
-- Additive columns (ADR-0012): ADD COLUMN IF NOT EXISTS does not fire the
-- append-only trigger (that fires on UPDATE/DELETE).
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS attestation  BYTEA;
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS attester_key BYTEA;

-- Node-local actor attribution (issue #99 / review A10). At admission each door
-- resolves the signer against the LOCAL actor registry; when that resolution is
-- UNIQUE, the admitting actor_id (ADR-0011: the content-address of the pinned
-- determinant set, skill_epoch included) is stamped here. When the key is
-- concurrently registered to several actors the stamp is NULL — attribution
-- honestly unknown (principle 4), never a guess. Derived, node-local state (like
-- recorded_at): NOT part of the signed bytes, never on the wire. It exists so a
-- contamination-cascade recall (ADR-0029/0030) can answer "which events did actor
-- (key, epoch) author?" exactly, even after a supersede re-registers the same key
-- under a new epoch; NULL rows are conservatively over-selected by
-- events_by_actor_epoch (db/006), never silently missed.
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS actor_id BYTEA;

CREATE INDEX IF NOT EXISTS event_log_order_idx
    ON event_log (hlc_wall, hlc_counter, node_origin);
CREATE INDEX IF NOT EXISTS event_log_patient_idx
    ON event_log (patient_id);

-- Does this chart exist yet? (§5.3/§5.8 precedence, ADR-0061 decision 3, issue #345.)
--
-- "The chart exists" is expressed as "the log holds at least one event for this patient" rather
-- than "a patient_registration row exists", and the difference is load-bearing: the REMOTE door
-- is lenient by design, so a chart can legitimately hold a peer's clinical event before the
-- registration licensing it has synced. Keying the rule on the projection would refuse the next
-- LOCAL write to such a chart — punishing this node for the wire's lack of ordering, which is
-- exactly the wedge ADR-0061 decision 3 exists to avoid.
--
-- LANGUAGE sql + STABLE so the planner inlines it into the caller as a plain EXISTS over
-- event_log_patient_idx: one indexed lookup on the write path, per submit.
CREATE OR REPLACE FUNCTION cairn_patient_has_events(p_patient_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT EXISTS (SELECT 1 FROM event_log WHERE patient_id = p_patient_id)
$$;
-- Locked down like every predicate the doors call: submit_event is SECURITY DEFINER and calls
-- this as the migration-defining owner, so no runtime role needs EXECUTE.
REVOKE EXECUTE ON FUNCTION cairn_patient_has_events(uuid) FROM PUBLIC;

-- The t_effective wire pin (issue #91 / review H4). t_effective travels inside the
-- signed body as a STRING; the naive `::timestamptz` cast of an offset-less string is
-- resolved under the session's TimeZone GUC, so the SAME signed event would denote a
-- DIFFERENT UTC instant on differently-configured nodes — a silent cross-node
-- divergence inside a signed artifact. Pin the wire format: an asserted t_effective
-- must be a full ISO-8601 instant WITH an explicit UTC offset ('Z' or ±HH[:MM]).
-- With the offset explicit (and the unambiguous ISO date shape), the cast below is
-- independent of both TimeZone and DateStyle, so every node stores the same instant.
-- Both admission doors (submit_event, apply_remote_event) route through this ONE
-- validator. Returns NULL for an absent/'null' claim (principle 4: unknown is honest).
CREATE OR REPLACE FUNCTION cairn_t_effective(p_raw text)
RETURNS timestamptz LANGUAGE plpgsql STABLE AS $$
BEGIN
    IF p_raw IS NULL OR p_raw = 'null' THEN
        RETURN NULL;
    END IF;
    IF p_raw !~ '^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|z|[+-]\d{2}(:?\d{2})?)$' THEN
        RAISE EXCEPTION
            't_effective "%" must be an ISO-8601 instant with an explicit UTC offset (e.g. 2026-06-20T10:00:00+02:00) — an offset-less timestamp names a different instant on different nodes (wire pin, issue #91/H4)',
            p_raw;
    END IF;
    RETURN p_raw::timestamptz;
END;
$$;

-- NOTE (safety-critical seam, §9 / ADR-0002): Ed25519 signature verification runs
-- IN-DATABASE (the cairn_pgx `cairn_verify` gate) at every admission door —
-- submit_event (db/005) for local authors and apply_remote_event (db/020, issue
-- #91) for replicated events — so it is *unbypassable*: no row enters event_log
-- unless its COSE_Sign1 verifies against a registered key. The content-address
-- CHECK above is the part that is expressible in core SQL.

-- Append-only enforcement (principle #1): refuse UPDATE and DELETE outright.
CREATE OR REPLACE FUNCTION event_log_is_append_only()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'event_log is append-only: % is not permitted (Cairn principle #1)', TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS event_log_no_update ON event_log;
CREATE TRIGGER event_log_no_update BEFORE UPDATE OR DELETE ON event_log
    FOR EACH ROW EXECUTE FUNCTION event_log_is_append_only();

-- ---------------------------------------------------------------------------
-- Per-node Hybrid Logical Clock (single row). Advanced on every local write
-- and merged forward on every applied remote event (§3.6, ADR-0003).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hlc_state (
    id          BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
    hlc_wall    BIGINT  NOT NULL DEFAULT 0,
    hlc_counter INTEGER NOT NULL DEFAULT 0
);
INSERT INTO hlc_state (id, hlc_wall, hlc_counter)
    VALUES (TRUE, 0, 0) ON CONFLICT (id) DO NOTHING;

-- The A3 clock merge: drag this node's HLC forward past an event we have just ADMITTED,
-- so the local clock never falls behind anything in our own log (§3.6, ADR-0003).
--
-- ONE copy, five callers (issue #227). This block used to be pasted verbatim into every
-- admission door — the three arms of apply_remote_node_event (db/007), restore_node_event
-- (db/009), and apply_remote_event (db/020). A later edit that fixed one copy and missed
-- another would leave two doors with DIFFERENT clock semantics: silent divergence between
-- the node plane and the clinical plane, exactly the class of drift the twin-registry
-- row-count already cost us once (PR #182).
--
-- IT LIVES IN db/001 ON PURPOSE, not next to the node door in db/007. hlc_state is created
-- here, and — the load-bearing half — cairn-sync loads a SUBSET of the migrations that
-- includes db/001 and db/020 but NOT db/007. PL/pgSQL binds a function call at first
-- EXECUTION, so declaring this in db/007 would let cairn-sync's schema load cleanly and
-- then fail on its first admitted event: a first-write outage, which is the trap issue
-- #198 was filed for.
--
-- WHAT THIS IS NOT: it is not the drift ceiling. Each door decides ADMISSION for itself
-- before calling this — db/007 and db/009 REJECT a too-future event, db/020 CLAMPS the
-- wall it passes in — because their pull loops react differently to a refusal (issues
-- #102/#193; the reasoning lives at each call site). Keeping this function the pure
-- monotone merge and nothing else is what stops one door accidentally inheriting
-- another's admission policy.
--
-- NOT A DOOR: it writes hlc_state, so the runtime must never be able to call it directly
-- — that would bypass the ceiling each door applies first, and one ratcheting connection
-- wedges this node out of the federation (every peer would refuse the far-future events
-- it then authors). Hence INVOKER rights, deliberately NOT SECURITY DEFINER, plus REVOKE
-- FROM PUBLIC: the SECURITY DEFINER doors call it as the migration-defining owner so no
-- grant is needed, and invoker rights leave a SECOND barrier standing if a future edit
-- ever GRANTs EXECUTE by mistake — cairn_node holds no UPDATE on hlc_state. Same pattern
-- as cairn_patient_has_events above.
-- ---------------------------------------------------------------------------
-- HOUSE RULE FOR EVERY `SET search_path` IN db/*.sql (#426, 2026-08-16).
-- Stated once, here, because this is the first pinned function in load order. Every other
-- site carries the clause; the sites where the reasoning is load-bearing (the dynamic-%I
-- dispatchers, the two write doors) point back here rather than restate the argument.
--
--   THE CLAUSE IS ALWAYS `SET search_path = public, pg_temp` — pg_temp LAST, never
--   the bare `public` form, and never pg_temp anywhere but last.
--
-- WHY. `SET search_path = public` reads like a lockdown and is not one. PostgreSQL
-- searches the session's TEMPORARY schema FIRST for relation and data-type names whenever
-- the path does not place pg_temp explicitly; the setting only controls where pg_temp sits
-- when you DO name it. PUBLIC holds TEMPORARY on every database by default (nothing in this
-- tree revokes it), so any role that can reach a function could `CREATE TEMP TABLE
-- event_log (…)` and have every unqualified relation name inside that function resolve
-- to its own decoy. PostgreSQL's own "Writing SECURITY DEFINER Functions Safely" calls
-- the temp schema out by name and prescribes writing pg_temp last.
--
-- WHAT IT COST BEFORE THE FIX — this was live, not theoretical, and it is reproduced as a
-- test rather than asserted here. Both owner-rights write doors (submit_event db/005,
-- apply_remote_event db/020) carried the bare form. With a decoy in place they RETURNED
-- SUCCESS while the owner-privileged INSERT landed in the caller's temp table: the client
-- was told the write succeeded, the append-only log never saw the event, no projection
-- trigger fired, and the row vanished at session end. Silent clinical data loss from a role
-- holding NO write privilege on event_log at all — only EXECUTE on the door plus the
-- TEMPORARY every role has by default.
--
-- Be exact about the local door's reach, because a bare decoy does not buy the whole attack:
-- submit_event step 8b (#345 precedence) reads event_log unqualified via
-- cairn_patient_has_events, so an EMPTY decoy blinds that check and makes any NON-registration
-- type fail LOUDLY ("no chart exists"). Registration diverts silently because 8b short-circuits
-- for it. Seeding the decoy with one row bearing the patient_id restores 8b and every type then
-- diverts silently. apply_remote_event has no 8b, so it diverts unconditionally. All three
-- cases are pinned in crates/cairn-node/tests/search_path_pg_temp.rs.
--
-- The same shadowing blinded db/049's safety readers into "no safety signals on file"
-- for a chart that carried one (the finding that opened #426).
--
-- WHY IT IS UNIFORM RATHER THAN PER-FUNCTION. Only bodies naming a relation unqualified
-- are exposed, but "does this body name a relation?" is a judgement that has to be
-- re-made on every edit and is silent when got wrong. A uniform clause is instead
-- mechanically checkable, and is checked: crates/cairn-node/tests/search_path_pg_temp.rs
-- asserts over pg_proc that EVERY pinned path denies the temp schema the first look (and
-- that every SECURITY DEFINER pins one at all), so a new migration is covered the moment it
-- loads. "Denies the first look" rather than "ends in pg_temp", because the naive form of
-- that rule waves through `SET search_path = pg_temp` — last element pg_temp, and the worst
-- possible path — and condemns `SET search_path = ''`, which is strictly better than this
-- house rule. Adding pg_temp costs nothing where no relation is named.
--
-- WHAT `pg_temp` LAST DOES *NOT* MAKE AIRTIGHT — state the residual rather than let a
-- reader infer a guarantee, and state the RIGHT one.
--
-- Closed outright: schema order decides RELATION and DATA TYPE lookup, which is the whole
-- of the implicit temp search (docs, "search_path": the temporary schema "is only searched
-- for relation … and data type names"). The demonstrated attack above is fully closed, and
-- so is the type-name variant nobody exercised.
--
-- NOT at issue, despite the intuition: FUNCTION and OPERATOR lookup. Postgres NEVER searches
-- the temporary schema for a function or operator name — not when pg_temp is unnamed, and
-- not when it is named, in any position. Verified on PG 18.1: a function existing only in
-- pg_temp raises `function f(integer) does not exist` under `public, pg_temp` AND under
-- `pg_temp, public`, while pg_temp.f(1) resolves fine and an unqualified temp RELATION
-- resolves fine in the same session. So naming pg_temp here exposes no call site, and no
-- body needs auditing for inexact-match calls on this account.
--
-- The residual that IS real: pg_temp last only wins a name that `public` actually HAS. An
-- unqualified relation absent from public still falls through to the caller's temp schema —
-- `to_regclass('not_in_public')` under `public, pg_temp` returns the temp relation. That
-- reaches the to_regclass(v_tbl) in cairn_check_projection_registry_fn (db/005), whose own
-- comment names the stake: a typo would silently exempt the real table from rebuild's
-- refusal check. Low severity today (that input path is owner-only and cairn_projection_apply
-- is REVOKEd from PUBLIC), but it is the residual, not a hypothetical about overloads.
--
-- The airtight form is `SET search_path = ''` with every name schema-qualified — it removes
-- any dependence on public itself being the schema that answers. That is a far larger and
-- more error-prone edit across these bodies (dynamic %I dispatch included) and is deliberately
-- not attempted here; the repo-wide guard accepts it wherever someone does attempt it.
--
-- WHY NOT `REVOKE TEMPORARY ON DATABASE … FROM PUBLIC` INSTEAD (#426 want 2, considered
-- and declined). It would close the same vector by taking the capability away, but at the
-- wrong layer and with the wrong blast radius: TEMPORARY is a general database facility a
-- FHIR façade or UI backend may legitimately want for staging work, and withdrawing it
-- fleet-wide to compensate for a clause we now assert repo-wide is policy dressed as
-- mechanism (principle 9 — Cairn ships mechanism; a deployment may still revoke it locally
-- if its own threat model wants belt and braces). It would also disarm the tests that PROVE
-- this fix: they create the decoy as the runtime roles themselves (cairn_agent at the local
-- door, cairn_node at the sync door) precisely to show no extra privilege is needed, and
-- cannot run in a database where nobody may.
--
-- WHAT THIS DOES NOT COVER, stated with the real size rather than one example. A function
-- with NO `SET search_path` resolves under the caller's path entirely, temp schema included.
-- That is not a one-function remainder: ~100 invoker-rights functions in this schema pin no
-- path, ~68 of them EXECUTE-able by cairn_agent. The reason it is a different problem, not
-- simply the rest of this one: an invoker-rights function runs with the CALLER's own
-- privilege, so shadowing it hands the caller nothing they did not already have — it is
-- self-deception, not escalation — and pinning a clause blocks SQL inlining on hot read
-- paths, which is the measured trade #420 still owes.
--
-- Two sharp edges inside that class, so nobody re-derives them:
--   * A function reached ONLY from inside a pinned definer inherits its caller's path and is
--     safe for that reason alone — cairn_patient_has_events, load-bearing for the #345
--     precedence check, is exactly this. Nothing guards that invariant; a future direct
--     GRANT would silently end it.
--   * Escalation would need such a function to be consulted by something trusted. Audited
--     2026-08-16: no RLS policy and no CHECK constraint in this schema calls one, so there
--     is no live path today. Tracked in #430.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION cairn_node_hlc_merge(p_wall BIGINT, p_counter INTEGER)
RETURNS void
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
    -- Fail closed on NULL. Left unguarded, a NULL degrades the whole statement into a
    -- silent no-op that LOOKS like it worked: GREATEST() ignores NULLs, and `NULL > x` is
    -- NULL (never true), so every branch below would fall through to "keep what we have".
    -- Unreachable from today's callers — node_event.hlc_wall and event_log.hlc_wall are
    -- NOT NULL and are inserted BEFORE the merge runs — but a function signature outlives
    -- the accident of ordering that makes it unreachable, and the next caller does not
    -- inherit it.
    IF p_wall IS NULL OR p_counter IS NULL THEN
        RAISE EXCEPTION 'cairn_node_hlc_merge: wall and counter must not be NULL (got %, %) — fail closed',
            p_wall, p_counter;
    END IF;
    -- Monotone by construction: the wall only ever rises; on a strictly higher incoming
    -- wall we ADOPT the incoming counter rather than keeping ours (a counter only orders
    -- events that share its wall, so ours says nothing against a wall it never saw); on a
    -- tie we keep the higher counter; on a lower wall nothing moves at all. Every SET
    -- expression reads the pre-UPDATE row, so the CASE sees the same hlc_wall the
    -- GREATEST beside it does.
    --
    -- Pairing the two arguments correctly is the CALLER's job, and one caller knowingly
    -- does not: db/020 hands over a CLAMPED wall with the event's raw counter, so on a
    -- clamped path the adopted counter was asserted against a wall we refused. That is
    -- deliberate and pre-dates this helper (see the clamp rationale there) — and it is
    -- bounded, because a counter only tiebreaks within a single millisecond and so cannot
    -- carry the clock past the ceiling the wall was just clamped to.
    UPDATE hlc_state SET
        hlc_wall    = GREATEST(hlc_wall, p_wall),
        hlc_counter = CASE
            WHEN p_wall > hlc_wall THEN p_counter
            WHEN p_wall = hlc_wall THEN GREATEST(hlc_counter, p_counter)
            ELSE hlc_counter END
        WHERE id;
END;
$$;
REVOKE EXECUTE ON FUNCTION cairn_node_hlc_merge(bigint, integer) FROM PUBLIC;

-- Decode a hex payload field, or refuse LEGIBLY (issue #228).
--
-- Node-plane payloads carry node-ids as hex strings, and three doors decode them:
-- submit_node_event and apply_remote_node_event (db/007) and restore_node_event (db/009).
-- All three guarded the NULL case — db/007's four guards by field name, db/009's with a
-- generic "missing subject node id" — and then handed the non-NULL MALFORMED case
-- straight to decode(), which raises PostgreSQL's own `invalid hexadecimal digit: "x"` —
-- no door, no field, no author. A trusted-but-buggy peer shipping
-- `"peer_node_id_hex": "0xABC"` produced an error indistinguishable from any other hex
-- failure in the session. The house rule the db/007 header states is *every rejection is
-- legible*, and this was the exception.
--
-- IT WAS ALSO A SYNC STALL, which issue #228 did not know. The pull loop classifies a
-- door's refusal BY SQLSTATE (crates/cairn-node/src/sync.rs): a bare `RAISE EXCEPTION`
-- (P0001) is a deliberate, self-healing deny-all → skip-and-advance, while any OTHER code
-- is read as a transient DB fault and FREEZES the cursor below that seq rather than risk
-- losing a valid event (#111 review, A1). A bare decode() raises in PostgreSQL's 22 class,
-- so one trusted-but-buggy peer shipping `"peer_node_id_hex": "0xABC"` froze node-plane
-- pull from that peer PERMANENTLY — re-fetched and re-frozen every cycle, logged as
-- "transient?". Routing through this helper makes the refusal P0001, so the malformed
-- event is skipped and sync continues.
--
-- THE P0001 IS THEREFORE A CONTRACT, not an accident of using RAISE EXCEPTION. Do not add
-- `USING ERRCODE = …` to any RAISE below to "preserve Postgres's own code": the reason is
-- already preserved as DETAIL, and re-adopting a 22-class code reinstates the freeze.
-- Pinned by hex_decode_helper.rs (`refuses_malformed_hex_with_the_skip_and_advance_code`)
-- and by the SQL mirror, because a message-only assertion would stay green through it.
--
-- THE SHAPE IS CHECKED UP FRONT, and decode() is then called on a value that cannot fail —
-- rather than wrapping decode() in `EXCEPTION WHEN others`. That is the house idiom, set
-- twice by review: db/034 validates a hex commitment with this same regex + even-length
-- pair precisely so decode() never raises a cryptic error, and db/041 had its
-- `EXCEPTION WHEN others` uuid catch replaced because a catch-all "could not tell
-- 'malformed input' from 'something else broke' apart, and always blamed the caller". The
-- objection is not that a handler swallows errors (this one re-raised everything) but that
-- it RELABELS them: an out-of-memory or an internal error inside decode() would have been
-- reported to an operator as "peer_node_id_hex is not valid hex", which is a worse
-- illegibility than the one this function exists to fix. Checking first also drops the
-- per-call subtransaction a BEGIN/EXCEPTION block costs.
--
-- Arguments read as a sentence at the call site: which FIELD, its VALUE, which DOOR.
--
-- IT LIVES IN db/001 for the same reason cairn_node_hlc_merge above does: cairn-sync loads
-- a SUBSET of the migrations that includes db/001 but not db/007 or db/009, and PL/pgSQL
-- binds a function call at first EXECUTION. Declaring a shared helper beside its current
-- callers is what turns a later clinical-plane call site into a first-write outage — the
-- late-binding trap of issue #198. Today's six call sites are all node-plane; a
-- decode-hex helper is exactly what the next door reaches for.
--
-- DELIBERATELY NOT `STRICT`: a STRICT function returns NULL on NULL input without ever
-- entering the body, which would skip the guard below and hand the caller's NOT NULL
-- column an opaque constraint error — reintroducing the illegibility this exists to end.
--
-- The refusal CHARACTERISES the value (its length + a strict prefix) instead of echoing it.
-- Node-ids are content addresses and carry nothing secret, so that is not a leak fix
-- today; it is the habit that keeps it from becoming one, because a general hex decoder is
-- what a later door will use for a key, a token or a wrapped DEK, and door errors are
-- written to logs that outlive the session. Length + prefix is also what a human debugging
-- a buggy peer actually needs: it separates "truncated" from "wrong encoding" at a glance.
CREATE OR REPLACE FUNCTION cairn_decode_hex_or_raise(p_field TEXT, p_value TEXT, p_door TEXT)
RETURNS BYTEA
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
    v_prefix TEXT;
    v_reason TEXT;
BEGIN
    IF p_value IS NULL THEN
        RAISE EXCEPTION '%: % is missing from the payload', p_door, p_field;
    END IF;

    -- Show at most half the value, and never more than 8 characters (4 bytes) — then say
    -- so with a trailing '...' that is ALWAYS truthful, because something is always
    -- hidden. Capping at 8 alone is not enough: it silently degrades to the whole value
    -- for anything 8 characters or shorter, which is precisely the short-secret case the
    -- paragraph above says this exists to protect (PR #371 review). Halving keeps the
    -- diagnosis intact where it matters — a '0x' prefix, a leading '-', a UUID's dashes
    -- all survive in the first characters — while nothing short is ever reproduced whole.
    v_prefix := left(p_value, LEAST(8, length(p_value) / 2)) || '...';

    -- Check the SHAPE first, so the decode below cannot fail (see the header: this is
    -- db/034's idiom, not an EXCEPTION handler that would relabel an unrelated internal
    -- error as bad caller input). The two arms are the two ways hex goes wrong, and
    -- naming which one is what tells a truncated value apart from a wrongly-encoded one.
    IF p_value !~ '^[0-9a-fA-F]*$' THEN
        v_reason := 'contains a character that is not a hex digit';
    ELSIF length(p_value) % 2 <> 0 THEN
        v_reason := 'has an odd number of hex digits, so it is not a whole number of bytes';
    END IF;
    IF v_reason IS NOT NULL THEN
        -- The reason goes in DETAIL, the same place these doors put cairn_verify_error();
        -- the MESSAGE stays the legible one, because that is the line a caller logs, and
        -- the SQLSTATE stays P0001, because that is the line the PULL LOOP reads (above).
        RAISE EXCEPTION '%: % is not valid hex (% chars, starts "%")',
            p_door, p_field, length(p_value), v_prefix
            USING DETAIL = v_reason;
    END IF;

    RETURN decode(p_value, 'hex');
END;
$$;
REVOKE EXECUTE ON FUNCTION cairn_decode_hex_or_raise(text, text, text) FROM PUBLIC;

-- A jsonb value coerced to a list, TOTALLY — this one never raises.
--
-- The permissive twin of db/027's cairn_json_list_or_raise, and the two are deliberately not the
-- same function: a door that is MINTING a field wants the refusal (the author is present and can
-- fix it), while a door that is STORING an already-signed field wants a value every reader can
-- walk. Absent, JSON null, a string, a number and an object all become the empty array; an array
-- passes through untouched.
--
-- WHY IT LIVES IN db/001 AND NOT BESIDE ITS SIBLING IN db/027: its callers are db/005 and db/020,
-- both of which LOAD EARLIER than db/027. PL/pgSQL resolves a call at first execution so the
-- forward reference would work, but a helper whose declaration a reader cannot reach by reading
-- downwards is the shape issue #198 was filed about, and db/001 is the one file every migration
-- subset loads. Its raising sibling stays in db/027, where its only callers are.
CREATE OR REPLACE FUNCTION cairn_json_list_or_empty(v jsonb)
RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE WHEN jsonb_typeof(v) = 'array' THEN v ELSE '[]'::jsonb END;
$$;

-- ---------------------------------------------------------------------------
-- Sync watermark per peer: the highest HLC this node has pulled from a peer.
-- Pull is a resumable set-union; the watermark is a hint, never an authority
-- (ADR-0004) — re-pulling from 0 must converge to the identical set.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sync_state (
    peer         TEXT    PRIMARY KEY,
    hlc_wall     BIGINT  NOT NULL DEFAULT 0,
    hlc_counter  INTEGER NOT NULL DEFAULT 0,
    last_pull_at TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- The admitted-uninterpreted marker (ADR-0056 decision 1, issue #265).
--
-- A 1:1 node-local sidecar of event_log. One row means: "this event was admitted
-- by the remote door WITHOUT its type being classified, so it holds NO power."
-- Node-local derived state — never signed, never on the wire (principle 12),
-- like reproject_log (db/039) and node_schema (db/038).
--
-- WHY EXPLICIT, rather than inferred from a missing event_type_class row:
-- ADR-0056's corollary forbids inferring the deferred state from a null
-- classification lookup falling through the gates by three-valued logic. An
-- inferred marker also has nowhere to record WHY a re-adjudication attempt
-- failed, which decision 4 requires to be flagged legibly.
--
-- WHY IT LIVES HERE rather than in this slice's own db/043: db/005's
-- cairn_replay_eligible and cairn_suppression_author_ok both read it, and both
-- are LANGUAGE sql — SQL-language function bodies resolve table names at CREATE
-- time (unlike PL/pgSQL's late binding), so the table must exist before db/005
-- loads. Its consumers are documented in db/043_deferred_readjudication.sql.
--
-- The row is DELETED on promotion, never marked resolved: its presence IS the
-- invariant ("powerless; the classification-gated checks have not been passed"),
-- and a resolved-row history would be a second, drift-prone source of truth for
-- the same fact.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_deferred (
    event_id           UUID PRIMARY KEY REFERENCES event_log(event_id) ON DELETE CASCADE,
    -- Denormalized from event_log so the reclassification scan selects its
    -- candidates by joining this against event_type_class alone, and the
    -- `cairn-node deferred` listing reads it without touching event_log.
    event_type         TEXT        NOT NULL,
    -- Node-local operational stamp (clock_timestamp, like reproject_log.ran_at).
    -- NEVER a clinical time: t_recorded/t_effective live on event_log and are the
    -- only times that mean anything about the record itself.
    admitted_at        TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    -- NULL until a re-adjudication attempt has run and FAILED; then the verbatim
    -- refusal. This column IS decision 4's "flagged legibly".
    adjudication_error TEXT,
    last_attempt_at    TIMESTAMPTZ
);

-- The reclassification scan joins event_deferred → event_type_class on this column.
CREATE INDEX IF NOT EXISTS event_deferred_type_idx ON event_deferred (event_type);

-- ---------------------------------------------------------------------------
-- The carried-not-vouched marker (ADR-0056, PR #302 review finding F2).
--
-- One row means: "this event_log row's attestation/attester_key were STORED
-- WITHOUT BEING VERIFIED." The remote door cannot verify a deferred event's
-- travelling token — the gate that would is deferred with the interpretation —
-- but it must store it, or cairn_readjudicate_deferred has nothing to verify
-- later and admit-and-defer degrades into a slower fail-closed.
--
-- WHY A SECOND TABLE, rather than reusing event_deferred: the two answer
-- DIFFERENT questions with DIFFERENT lifetimes.
--   event_deferred                 -> "has this event been adjudicated?"
--   event_attestation_unvouched    -> "is this event's stored token vouched?"
-- Promotion deletes the first. The second must SURVIVE it, because db/043's
-- gate 1 only verifies a token when the type's mode DEMANDS one — an additive
-- event bearing no responsibility promotes with its token never checked. Using
-- event_deferred as the proxy is precisely the F2 defect: it let a forged token
-- on an unknown-type event put any key inside the target's human-author set
-- once the type was classified.
--
-- Node-local derived state — never signed, never on the wire (principle 12),
-- like event_deferred, reproject_log (db/039) and node_schema (db/038).
--
-- Deleted, never marked resolved, for the same reason event_deferred is: its
-- presence IS the invariant, and a resolved-row history would be a second,
-- drift-prone source of truth for one fact. Its readers are documented at the
-- three call sites (db/005 cairn_suppression_author_ok, db/018
-- patient_link_apply, db/034 medication_attestation_apply); a new reader of
-- event_log.attestation / .attester_key owes the same exclusion.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_attestation_unvouched (
    event_id UUID PRIMARY KEY REFERENCES event_log(event_id) ON DELETE CASCADE
);

-- The ONE way to ask "is this row's stored attestation a real vouch?" (house rule 4).
--
-- Four readers need it — db/005's cairn_suppression_author_ok, db/018's patient_link_apply
-- (twice) and db/034's medication_attestation_apply — and a fifth will arrive with the next
-- type that reads event_log.attester_key. Four hand-written copies of one predicate is four
-- places to change in step; a named function makes each call site read as the QUESTION being
-- asked rather than the mechanism, which is the point of the marker.
--
-- Lives HERE, in db/001, because db/005's cairn_suppression_author_ok is LANGUAGE sql, whose
-- body resolves table AND function names at CREATE time — the same reason the table is here.
-- LANGUAGE sql STABLE so it INLINES: db/005's predicate still folds into cairn_reproject's
-- per-type anti-join instead of costing a call per replayed event.
CREATE OR REPLACE FUNCTION cairn_attestation_vouched(p_event_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT NOT EXISTS (SELECT 1 FROM event_attestation_unvouched u
                        WHERE u.event_id = p_event_id)
$$;
-- Locked down like cairn_replay_eligible (db/005): every caller is a SECURITY DEFINER door or
-- a migration-owned trigger, so no runtime role needs a grant, and PUBLIC's default EXECUTE
-- would let any connected role probe a safety predicate.
REVOKE EXECUTE ON FUNCTION cairn_attestation_vouched(uuid) FROM PUBLIC;

COMMIT;
