-- Cairn walking skeleton — the signed event envelope (Spike 0001 §3, §4).
--
-- This is the *day-one, can't-retrofit* shape: every column here is reserved
-- because an append-only log cannot grow these later without rewriting history
-- (the same reason t_effective and the encryption-capable body slot are day-one
-- in data-model §3.5/§3.6/§3.8). The walking skeleton exists to exercise this
-- shape on real hardware over a real link before it is frozen into an ADR.
--
-- Relationship to poc/replication-failover: that PoC proved set-union
-- convergence with a *bare* event_log (no signatures, projections-as-views).
-- This skeleton wraps the signed COSE_Sign1 envelope around the same HLC-ordered
-- log, adds an in-database content-address invariant, a trigger-maintained
-- projection (002), and a BLAKE3 content-addressed blob tier (003).
--
-- Target: PostgreSQL >= 18 (uuidv7(), the project floor). Loaded identically
-- into every node; a node's identity is just the string it stamps on origin.

BEGIN;

-- Content-addressing and the legibility twin lean on pgcrypto's digest().
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Maximum size of one signed event, enforced at EVERY admission door (submit_event,
-- submit_node_event, apply_remote_node_event, restore_node_event). This is the WRITE-side
-- counterpart of the wire/backup read caps (sync.rs MAX_FRAME_BYTES / medium.rs
-- MAX_CHUNK_BYTES, both 8 MiB): those caps REFUSE an oversized event on read, and because
-- a puller aborts mid-stream without checkpointing, a single oversized-but-admitted event
-- would wedge sync at that seq forever AND could clobber a good backup medium. Refusing
-- oversize at admission makes that unreachable — the read caps become true dead paths for
-- honest data. Set below the 8 MiB (8,388,608-byte) frame cap with headroom for framing.
-- (Review finding A7a. Attachments are content-addressed blobs on the byte tier, NOT
-- inlined here, so a legitimate clinical event never approaches this bound — ADR-0013.)
CREATE OR REPLACE FUNCTION cairn_max_event_bytes()
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 8000000 $$;

-- The clock-drift admission ceiling (issue #102), in milliseconds. The largest amount
-- a REMOTE event's asserted HLC wall may sit ahead of THIS node's own wall clock and
-- still be trusted to advance the local clock. Both remote-apply doors merge the local
-- HLC forward with GREATEST(local_wall, remote_wall) (the A3 invariant — the clock never
-- falls behind an accepted event); without a ceiling, ONE verified event from a
-- trusted-but-broken or hostile peer carrying an absurd future wall (e.g. 2^62 ms ≈ 146
-- million years) permanently ratchets this node's clock — and, on the node plane, poisons
-- trust_peer's `ORDER BY hlc_wall DESC` — into the far future, with no self-healing path
-- (GREATEST is monotone; real time never catches up). 24h is deliberately generous: it
-- admits any plausible honest clock skew (an unsynced peer, a timezone-as-UTC bug, an
-- offline node whose RTC drifted) — consonant with ADR-0027, where a low-confidence clock
-- is BRACKETED, never treated as falsification — while still defeating the ratchet: an
-- attacker can push the local clock at most ~24h past real time, and that excess decays as
-- real time advances, rather than persisting for geological spans. Measured against
-- clock_timestamp() (the node's own wall clock), NOT the possibly-already-advanced
-- hlc_state, so the bound is absolute rather than itself ratchetable. Applies ONLY to the
-- remote-apply doors: a node's own authored events are its own clock's truth
-- (node_hlc_tick is already bounded by the local clock_timestamp).
CREATE OR REPLACE FUNCTION cairn_max_hlc_drift_ms()
RETURNS bigint LANGUAGE sql IMMUTABLE AS $$ SELECT 86400000 $$;  -- 24 * 60 * 60 * 1000

-- ---------------------------------------------------------------------------
-- The append-only, signed clinical event log (governing principle #1).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_log (
    -- Identity & causal order ------------------------------------------------
    event_id        UUID    PRIMARY KEY,        -- UUIDv7, generated by the signer; INSIDE the signed bytes
    patient_id      UUID    NOT NULL,           -- the immortal subject UUID this event is about
    event_type      TEXT    NOT NULL,           -- 'patient.created' | 'patient.amended' | 'note.added' | ...
    schema_version  TEXT    NOT NULL,           -- §3.13 join key; additive-only evolution

    -- Bitemporal time (§3.6): t_recorded is the HLC ceiling; t_effective is the
    -- freely-backdatable *claim* (NULL = not asserted / unknown — principle 4).
    hlc_wall        BIGINT  NOT NULL,           -- t_recorded: physical component (ms)
    hlc_counter     INTEGER NOT NULL,           -- t_recorded: logical tiebreak
    node_origin     TEXT    NOT NULL,           -- which node FIRST recorded (third sort key)
    t_effective     TIMESTAMPTZ,                -- asserted effective time; NULL-able on purpose

    -- The signed artifact (§4, structural move 1) ----------------------------
    -- signed_bytes IS the event: a COSE_Sign1 (RFC 9052) wire blob whose payload
    -- is the canonical-CBOR body. It is stored verbatim and NEVER re-serialized;
    -- everything below is a *derived view* of it, for indexing and projection.
    signed_bytes    BYTEA   NOT NULL,
    -- Self-describing content address (§4 move 2): multihash(sha2-256) of the
    -- signed bytes. The hash IS the event's identity, exactly as in §3.14.
    content_address BYTEA   NOT NULL UNIQUE,

    -- Derived view of the signed body (JSONB) — parsed FROM signed_bytes by the
    -- applying node, never authoritative, never round-tripped back to bytes.
    body            JSONB   NOT NULL,
    -- §3.9 contributor set (skeleton: a single author is enough). signer_key_id
    -- selects the verifying key; verification happens on apply (Bet A2), and in
    -- production moves in-DB via the ADR-0002 pgrx hatch (see note below).
    contributors    JSONB   NOT NULL,
    signer_key_id   TEXT    NOT NULL,

    -- §3.13 mandatory plaintext legibility twin (also the FTS/RAG substrate).
    plaintext_twin  TEXT    NOT NULL,

    -- Encryption-capable body slot (§3.8 / ADR-0005), stubbed off in the
    -- skeleton: sealed=false, dek_wrapped=NULL. Reserved day-one so crypto-shred
    -- can be added without an envelope change.
    sealed          BOOLEAN NOT NULL DEFAULT FALSE,
    dek_wrapped     BYTEA,

    -- §3.14 attachment references: an array of {alg, digest, media_type,
    -- descriptor}. The reference is eager (here); the BYTES are lazy (003).
    attachments     JSONB   NOT NULL DEFAULT '[]'::jsonb,

    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),  -- local arrival

    -- Content-address invariant, enforced in the database (§4 move 1 + §3.14):
    -- a row whose advertised address does not match its bytes is refused at the
    -- boundary. multihash prefix 0x12 0x20 = sha2-256, 32 bytes.
    CONSTRAINT event_content_addressed
        CHECK (content_address = '\x1220'::bytea || digest(signed_bytes, 'sha256')),
    -- t_recorded is a ceiling: the asserted effective time may precede it
    -- (backdating is legal) but the log never claims to have recorded the
    -- future. Clashes are flagged elsewhere, never auto-resolved (§3.6).
    CONSTRAINT hlc_nonnegative CHECK (hlc_wall >= 0 AND hlc_counter >= 0)
);

-- The responsibility proof travels WITH the event (issue #91 / review A2+M7). A
-- suppressing event (or any asserted responsibility) is admitted only against a valid
-- human attestation token bound to its content-address; if that token were verified
-- and discarded (the pre-#91 behavior), a downstream node re-serving the event could
-- never re-prove the responsibility, and the apply door could not re-run the gate.
-- So the token (and the attester's pubkey) are stored beside the signed bytes and
-- shipped on the clinical sync wire. NULL for events that needed no attestation.
-- Additive columns (ADR-0012): ADD COLUMN IF NOT EXISTS does not fire the
-- append-only trigger (that fires on UPDATE/DELETE).
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS attestation  BYTEA;
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS attester_key BYTEA;

-- Node-local actor attribution (issue #99 / review A10). At admission each door
-- resolves the signer against the LOCAL actor registry; when that resolution is
-- UNIQUE, the admitting actor_id (ADR-0011: the content-address of the pinned
-- determinant set, skill_epoch included) is stamped here. When the key is
-- concurrently registered to several actors the stamp is NULL — attribution
-- honestly unknown (principle 4), never a guess. Derived, node-local state (like
-- recorded_at): NOT part of the signed bytes, never on the wire. It exists so a
-- contamination-cascade recall (ADR-0029/0030) can answer "which events did actor
-- (key, epoch) author?" exactly, even after a supersede re-registers the same key
-- under a new epoch; NULL rows are conservatively over-selected by
-- events_by_actor_epoch (db/006), never silently missed.
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS actor_id BYTEA;

CREATE INDEX IF NOT EXISTS event_log_order_idx
    ON event_log (hlc_wall, hlc_counter, node_origin);
CREATE INDEX IF NOT EXISTS event_log_patient_idx
    ON event_log (patient_id);

-- The t_effective wire pin (issue #91 / review H4). t_effective travels inside the
-- signed body as a STRING; the naive `::timestamptz` cast of an offset-less string is
-- resolved under the session's TimeZone GUC, so the SAME signed event would denote a
-- DIFFERENT UTC instant on differently-configured nodes — a silent cross-node
-- divergence inside a signed artifact. Pin the wire format: an asserted t_effective
-- must be a full ISO-8601 instant WITH an explicit UTC offset ('Z' or ±HH[:MM]).
-- With the offset explicit (and the unambiguous ISO date shape), the cast below is
-- independent of both TimeZone and DateStyle, so every node stores the same instant.
-- Both admission doors (submit_event, apply_remote_event) route through this ONE
-- validator. Returns NULL for an absent/'null' claim (principle 4: unknown is honest).
CREATE OR REPLACE FUNCTION cairn_t_effective(p_raw text)
RETURNS timestamptz LANGUAGE plpgsql STABLE AS $$
BEGIN
    IF p_raw IS NULL OR p_raw = 'null' THEN
        RETURN NULL;
    END IF;
    IF p_raw !~ '^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?(Z|z|[+-]\d{2}(:?\d{2})?)$' THEN
        RAISE EXCEPTION
            't_effective "%" must be an ISO-8601 instant with an explicit UTC offset (e.g. 2026-06-20T10:00:00+02:00) — an offset-less timestamp names a different instant on different nodes (wire pin, issue #91/H4)',
            p_raw;
    END IF;
    RETURN p_raw::timestamptz;
END;
$$;

-- NOTE (safety-critical seam, §9 / ADR-0002): Ed25519 signature verification runs
-- IN-DATABASE (the cairn_pgx `cairn_verify` gate) at every admission door —
-- submit_event (db/005) for local authors and apply_remote_event (db/020, issue
-- #91) for replicated events — so it is *unbypassable*: no row enters event_log
-- unless its COSE_Sign1 verifies against a registered key. The content-address
-- CHECK above is the part that is expressible in core SQL.

-- Append-only enforcement (principle #1): refuse UPDATE and DELETE outright.
CREATE OR REPLACE FUNCTION event_log_is_append_only()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'event_log is append-only: % is not permitted (Cairn principle #1)', TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS event_log_no_update ON event_log;
CREATE TRIGGER event_log_no_update BEFORE UPDATE OR DELETE ON event_log
    FOR EACH ROW EXECUTE FUNCTION event_log_is_append_only();

-- ---------------------------------------------------------------------------
-- Per-node Hybrid Logical Clock (single row). Advanced on every local write
-- and merged forward on every applied remote event (§3.6, ADR-0003).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hlc_state (
    id          BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
    hlc_wall    BIGINT  NOT NULL DEFAULT 0,
    hlc_counter INTEGER NOT NULL DEFAULT 0
);
INSERT INTO hlc_state (id, hlc_wall, hlc_counter)
    VALUES (TRUE, 0, 0) ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Sync watermark per peer: the highest HLC this node has pulled from a peer.
-- Pull is a resumable set-union; the watermark is a hint, never an authority
-- (ADR-0004) — re-pulling from 0 must converge to the identical set.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sync_state (
    peer         TEXT    PRIMARY KEY,
    hlc_wall     BIGINT  NOT NULL DEFAULT 0,
    hlc_counter  INTEGER NOT NULL DEFAULT 0,
    last_pull_at TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- The admitted-uninterpreted marker (ADR-0056 decision 1, issue #265).
--
-- A 1:1 node-local sidecar of event_log. One row means: "this event was admitted
-- by the remote door WITHOUT its type being classified, so it holds NO power."
-- Node-local derived state — never signed, never on the wire (principle 12),
-- like reproject_log (db/039) and node_schema (db/038).
--
-- WHY EXPLICIT, rather than inferred from a missing event_type_class row:
-- ADR-0056's corollary forbids inferring the deferred state from a null
-- classification lookup falling through the gates by three-valued logic. An
-- inferred marker also has nowhere to record WHY a re-adjudication attempt
-- failed, which decision 4 requires to be flagged legibly.
--
-- WHY IT LIVES HERE rather than in this slice's own db/043: db/005's
-- cairn_replay_eligible and cairn_suppression_author_ok both read it, and both
-- are LANGUAGE sql — SQL-language function bodies resolve table names at CREATE
-- time (unlike PL/pgSQL's late binding), so the table must exist before db/005
-- loads. Its consumers are documented in db/043_deferred_readjudication.sql.
--
-- The row is DELETED on promotion, never marked resolved: its presence IS the
-- invariant ("powerless; the classification-gated checks have not been passed"),
-- and a resolved-row history would be a second, drift-prone source of truth for
-- the same fact.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_deferred (
    event_id           UUID PRIMARY KEY REFERENCES event_log(event_id) ON DELETE CASCADE,
    -- Denormalized from event_log so the reclassification scan selects its
    -- candidates by joining this against event_type_class alone, and the
    -- `cairn-node deferred` listing reads it without touching event_log.
    event_type         TEXT        NOT NULL,
    -- Node-local operational stamp (clock_timestamp, like reproject_log.ran_at).
    -- NEVER a clinical time: t_recorded/t_effective live on event_log and are the
    -- only times that mean anything about the record itself.
    admitted_at        TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    -- NULL until a re-adjudication attempt has run and FAILED; then the verbatim
    -- refusal. This column IS decision 4's "flagged legibly".
    adjudication_error TEXT,
    last_attempt_at    TIMESTAMPTZ
);

-- The reclassification scan joins event_deferred → event_type_class on this column.
CREATE INDEX IF NOT EXISTS event_deferred_type_idx ON event_deferred (event_type);

-- ---------------------------------------------------------------------------
-- The carried-not-vouched marker (ADR-0056, PR #302 review finding F2).
--
-- One row means: "this event_log row's attestation/attester_key were STORED
-- WITHOUT BEING VERIFIED." The remote door cannot verify a deferred event's
-- travelling token — the gate that would is deferred with the interpretation —
-- but it must store it, or cairn_readjudicate_deferred has nothing to verify
-- later and admit-and-defer degrades into a slower fail-closed.
--
-- WHY A SECOND TABLE, rather than reusing event_deferred: the two answer
-- DIFFERENT questions with DIFFERENT lifetimes.
--   event_deferred                 -> "has this event been adjudicated?"
--   event_attestation_unvouched    -> "is this event's stored token vouched?"
-- Promotion deletes the first. The second must SURVIVE it, because db/043's
-- gate 1 only verifies a token when the type's mode DEMANDS one — an additive
-- event bearing no responsibility promotes with its token never checked. Using
-- event_deferred as the proxy is precisely the F2 defect: it let a forged token
-- on an unknown-type event put any key inside the target's human-author set
-- once the type was classified.
--
-- Node-local derived state — never signed, never on the wire (principle 12),
-- like event_deferred, reproject_log (db/039) and node_schema (db/038).
--
-- Deleted, never marked resolved, for the same reason event_deferred is: its
-- presence IS the invariant, and a resolved-row history would be a second,
-- drift-prone source of truth for one fact. Its readers are documented at the
-- three call sites (db/005 cairn_suppression_author_ok, db/018
-- patient_link_apply, db/034 medication_attestation_apply); a new reader of
-- event_log.attestation / .attester_key owes the same exclusion.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_attestation_unvouched (
    event_id UUID PRIMARY KEY REFERENCES event_log(event_id) ON DELETE CASCADE
);

-- The ONE way to ask "is this row's stored attestation a real vouch?" (house rule 4).
--
-- Four readers need it — db/005's cairn_suppression_author_ok, db/018's patient_link_apply
-- (twice) and db/034's medication_attestation_apply — and a fifth will arrive with the next
-- type that reads event_log.attester_key. Four hand-written copies of one predicate is four
-- places to change in step; a named function makes each call site read as the QUESTION being
-- asked rather than the mechanism, which is the point of the marker.
--
-- Lives HERE, in db/001, because db/005's cairn_suppression_author_ok is LANGUAGE sql, whose
-- body resolves table AND function names at CREATE time — the same reason the table is here.
-- LANGUAGE sql STABLE so it INLINES: db/005's predicate still folds into cairn_reproject's
-- per-type anti-join instead of costing a call per replayed event.
CREATE OR REPLACE FUNCTION cairn_attestation_vouched(p_event_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
    SELECT NOT EXISTS (SELECT 1 FROM event_attestation_unvouched u
                        WHERE u.event_id = p_event_id)
$$;
-- Locked down like cairn_replay_eligible (db/005): every caller is a SECURITY DEFINER door or
-- a migration-owned trigger, so no runtime role needs a grant, and PUBLIC's default EXECUTE
-- would let any connected role probe a safety predicate.
REVOKE EXECUTE ON FUNCTION cairn_attestation_vouched(uuid) FROM PUBLIC;

COMMIT;
